=== sttyerase/Prober/src/main/resources/ProbeConfig.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:annotation>
    <xsd:documentation xml:lang="en">
      Schema definition for a Serviceprobe configuration file
      Copyright 2021 D.B. Moore. All rights reserved.
    </xsd:documentation>
  </xsd:annotation>

  <xsd:element name="probeconfig" type="probeconfigtype"/>

  <xsd:complexType name="probeconfigtype">
    <xsd:sequence>
      <xsd:element name="listenerport" type="listenerporttype"/>
      <xsd:element name="service" type="servicetype"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="listenerporttype">
    <xsd:attribute name="portnumber" type="xsd:positiveInteger"/>
  </xsd:complexType>

  <xsd:complexType name="infologtype">
    <xsd:attribute name="path" type="xsd:string"/>
    <xsd:attribute name="filename" type="xsd:string"/>
    <xsd:attribute name="loglevel" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="servicetype">
    <xsd:sequence>
      <xsd:element name="target" type="targettype"/>
      <xsd:element name="alert" type="alerttype"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="targettype">
    <xsd:sequence>
      <xsd:element name="infolog" type="infologtype"/>
      <xsd:element name="server"  type="servertype"/>
      <xsd:element name="proberate" type="proberatetype"/>
      <xsd:element name="protocol" type="protocoltype"/>
    </xsd:sequence>
    <xsd:attribute name="targettype" type="xsd:string"/> <!-- NOTE: targettype has double usage here. To be fixed -->
    <xsd:attribute name="secure" type="xsd:string"/>
    <xsd:attribute name="id" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="servertype">
    <xsd:attribute name="servername" type="xsd:string"/>
    <xsd:attribute name="portnumber" type="xsd:positiveInteger"/>
  </xsd:complexType>

  <xsd:complexType name="proberatetype">
    <xsd:attribute name="cycle" type="xsd:positiveInteger"/>
    <xsd:attribute name="unitsize" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="protocoltype">
    <xsd:sequence>
      <xsd:element name="request" type="requesttype"/>
      <xsd:element name="response" type="responsetype"/>
    </xsd:sequence>
    <xsd:attribute name="type" type="xsd:string"/>
    <xsd:attribute name="version" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="requesttype">
    <xsd:sequence>
      <xsd:element name="requesturl" type="requesturltype"/>
    </xsd:sequence>
    <xsd:attribute name="type" type="xsd:string"/>
    <xsd:attribute name="method" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="requesturltype">
    <xsd:attribute name="value" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="responsetype">
    <xsd:attribute name="type" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="alerttype">
    <xsd:sequence>
      <xsd:element name="alerter" type="alertertype"/>
      <xsd:element name="repeat" type="repeattype"/>
      <xsd:element name="message" type="messagetype"/>
      <xsd:element name="blackout" type="blackouttype"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="alertertype">
    <xsd:sequence>
      <xsd:element name="who" type="whotype"/>
    </xsd:sequence>
    <xsd:attribute name="transport" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="repeattype">
    <xsd:attribute name="type" type="xsd:string"/>
    <xsd:attribute name="number" type="xsd:positiveInteger"/>
    <xsd:attribute name="reset" type="xsd:positiveInteger"/>
    <xsd:attribute name="unit" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="whotype">
    <xsd:attribute name="addressee" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="messagetype">
    <xsd:attribute name="type" type="xsd:string"/>
    <xsd:attribute name="errtype" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="blackouttype">
    <xsd:attribute name="days" type="xsd:string"/>
    <xsd:attribute name="starttime" type="xsd:positiveInteger"/>
    <xsd:attribute name="endtime" type="xsd:positiveInteger"/>
  </xsd:complexType>

  <xsd:element name="debug" type="xsd:boolean"/>
</xsd:schema>

=== sttyerase/Prober/src/main/resources/ConfigExample03.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!-- THIS IS A PROTOTYPE CONFIG FILE FOR THE SERVICEPROBE -->
<probeconfig schemaLocation="ProbeConfig.xsd">
  <listenerport portnumber="27003" />
  <service>
    <target targettype="ldap_service" secure="false" id="dbmiserver"> <!--  implemented types: HTTP_Server  -->
      <infolog path="." filename="dbmiserver_ldap.log" loglevel="INFO"/>
      <server servername="dbmiserver" portnumber="4801"/>
      <proberate cycle="120" unitsize="default"/> <!-- DEFAULT=second : implemented: second,minute,hour -->
      <protocol type="LDAP">
        <request type="command" method="PING">
          <requesturl value="/"/>
        </request>
        <response type="String">HTTP/1.1 200 OK</response>
      </protocol>
    </target>
    <alert>
      <alerter transport="email"> <!-- implemented types =  email -->
        <who addressee="dbmi@techie.com"/>
      </alerter>
      <repeat type="LIMITED" number="3" reset="3" unit="hours"/>
      <message type="text" errtype="default">The server has encountered an unspecified error. Please verify that it is running.</message>
      <!-- INDIVIDUAL DAYS OVERRIDE WEEKEND OR WEEKDAY SETTINGS -->
      <blackout days="ALLDAYS"  starttime="0000" endtime="0615" />
      <blackout days="WEEKDAYS" starttime="2130" endtime="2359" />
      <blackout days="WEEKDAYS" starttime="0000" endtime="0530" />
      <blackout days="WEEKENDS" starttime="0000" endtime="0930" />
      <blackout days="WEEKENDS" starttime="1630" endtime="2359" />
      <blackout days="FRIDAY"   starttime="0500" endtime="0900" />
      <blackout days="TUESDAY"  starttime="1500" endtime="2330" />
      <blackout days="SUNDAY"   starttime="0900" endtime="1600" />
    </alert>
  </service>
</probeconfig>

        <!-- <debug/> if present set probe to provide additional debug information ::: TO BE IMPLEMENTED -->

=== sttyerase/Prober/src/main/resources/ConfigExample01.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!-- THIS IS A PROTOTYPE CONFIG FILE FOR THE SERVICEPROBE -->
<probeconfig schemaLocation="ProbeConfig.xsd">
  <listenerport portnumber="27001" />
  <service>
    <target targettype="HTTP" secure="false" id="dbmiserver"> <!--  implemented types: HTTP_Server  -->
      <infolog path="." filename="dbmiserver.log" loglevel="INFO"/>
      <server servername="dbmiserver" portnumber="3838"/>
      <proberate cycle="120" unitsize="default"/> <!-- DEFAULT=second : implemented: second,minute,hour -->
      <protocol type="HTTP" version="1.1">
        <request type="String" method="HEAD">
          <requesturl value="/"/>
        </request>
        <response type="String">HTTP/1.1 200 OK</response>
      </protocol>
    </target>
    <alert>
      <alerter transport="email"> <!-- implemented types =  email -->
        <who addressee="dbmi@techie.com"/>
      </alerter>
      <repeat type="LIMITED" number="3" reset="3" unit="hours"/>
      <message type="text" errtype="default">The HTTP server has encountered an unspecified error. Please verify that it is running.</message>
      <message type="text" errtype="NOT FOUND">The HTTP server was unable to locate the requested resource: </message>
      <message type="text" errtype="IOException">The HTTP server refused the request to connect: </message>
      <!-- INDIVIDUAL DAYS OVERRIDE WEEKEND OR WEEKDAY SETTINGS -->
      <blackout days="ALLDAYS"  starttime="0000" endtime="0615" />
      <blackout days="WEEKDAYS" starttime="2130" endtime="2359" />
      <blackout days="WEEKDAYS" starttime="0000" endtime="0530" />
      <blackout days="WEEKENDS" starttime="0000" endtime="0930" />
      <blackout days="WEEKENDS" starttime="1630" endtime="2359" />
      <blackout days="FRIDAY"   starttime="0500" endtime="0900" />
      <blackout days="TUESDAY"  starttime="1500" endtime="2330" />
      <blackout days="SUNDAY"   starttime="0900" endtime="1600" />
    </alert>
  </service>
</probeconfig>

        <!-- <debug/> if present set probe to provide additional debug information ::: TO BE IMPLEMENTED -->

=== sttyerase/Prober/src/main/resources/ConfigExample02.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!-- THIS IS A PROTOTYPE CONFIG FILE FOR THE SERVICEPROBE -->
<probeconfig schemaLocation="ProbeConfig.xsd">
  <listenerport portnumber="27002" />
  <service>
    <target targettype="simple_server" secure="false" id="dbmiserver"> <!--  implemented types: HTTP_Server  -->
      <infolog path="." filename="dbmiserver_ping.log" loglevel="INFO"/>
      <server servername="dbmiserver" portnumber="0000"/>
      <proberate cycle="120" unitsize="default"/> <!-- DEFAULT=second : implemented: second,minute,hour -->
      <protocol type="PING">
        <request type="ping"/>
        <response type="exit_code" value="2"/>
      </protocol>
    </target>
    <alert>
      <alerter transport="email"> <!-- implemented types =  email -->
        <who addressee="dbmi@techie.com"/>
      </alerter>
      <repeat type="LIMITED" number="3" reset="3" unit="hours"/>
      <message type="text" errtype="default">The server has encountered an unspecified error. Please verify that it is running.</message>
      <!-- INDIVIDUAL DAYS OVERRIDE WEEKEND OR WEEKDAY SETTINGS -->
      <blackout days="ALLDAYS"  starttime="0000" endtime="0615" />
      <blackout days="WEEKDAYS" starttime="2130" endtime="2359" />
      <blackout days="WEEKDAYS" starttime="0000" endtime="0530" />
      <blackout days="WEEKENDS" starttime="0000" endtime="0930" />
      <blackout days="WEEKENDS" starttime="1630" endtime="2359" />
      <blackout days="FRIDAY"   starttime="0500" endtime="0900" />
      <blackout days="TUESDAY"  starttime="1500" endtime="2330" />
      <blackout days="SUNDAY"   starttime="0900" endtime="1600" />
    </alert>
  </service>
</probeconfig>

        <!-- <debug/> if present set probe to provide additional debug information ::: TO BE IMPLEMENTED -->
